base.url=http://corp-gateway-dev.moscow.alfaintra.net

client.id=nib-corp-ncinsurance-accounting
client.secret=nib_corp_ncinsurance_accounting

ab.contract.account-program-id=1
ab.contract.debit-account-number=43523463456734576458
ab.contract.seller-id=U_M34NN
ab.contract.account.duration=12
ab.contract.account.payment-type=payment_account
ab.contract.account.insurance-sum=123000
ab.contract.account.insurance-premium=10000
ab.contract.account.seller-channel=SFA
ab.contract.account.contract-link=https://test.local/contract.pdf
ab.contract.account.policy-link=https://test.local/policy.pdf
ab.contract.account.agreement-link=https://test.local/agreement.pdf
ab.contract.account.owner-inn=7701234567
ab.contract.account.owner-phone-number=79999999999
ab.contract.account.owner-email=test@example.ru
ab.contract.account.owner-legal-address=Москва, улица Тестовая д.1
ab.contract.account.payment-account=40702810900000000001

ab.header.user-id=123456
ab.header.customer-id=123456
ab.header.client-type=MOBILE
ab.header.channel-id=INTERNET